// Copy-ready localized listing fields and a portable HTML guide for the release package.
const fs=require('fs'),path=require('path');
const out='D:/Game/Release/Store-1.6.0';fs.mkdirSync(out,{recursive:true});
const fields={
 ru:{
  title:'Вор времени',
  seo:'Кради секунды у хранителей времени, выбирай между кликами и магией, улучшай героя и побеждай боссов в бесконечном фэнтези-кликере.',
  short:'Кради секунды, меняй тактику и побеждай хранителей времени.',
  about:'Твоё время — и здоровье, и оружие. Каждая секунда на счету: хранители постоянно забирают её себе, а ты возвращаешь лишь часть нанесённого урона.\n\nАтакуй кликами или удерживай, чтобы колдовать. Враги почти неуязвимы к своему типу урона, поэтому следи за подсказкой и меняй тактику. Покупай за своё время вместимость часов, силу атаки, броню и магическую защиту. Выбирай дары боссов и собирай собственный набор усилений.\n\nТебя ждут 16 видов обычных противников, 10 особых боссов, меняющиеся условия боя и всё более опасные уровни. У каждого босса своя тактика: цели, печати, ритм и перегрев. На половине времени начинается вторая фаза. После последнего хранителя приключение продолжается: попробуй превзойти свой рекорд.\n\nПрогресс сохраняется автоматически. После поражения можно один раз за забег вернуться к жизни за просмотр рекламы, если она доступна.',
  how:'На компьютере кликай по врагу левой кнопкой мыши для физической атаки. Удерживай кнопку для магии. На телефоне используй короткие касания и удержание пальца.\n\nЗначок руки рядом с противником подсказывает нужное действие: клик или удержание. Следи за ним — некоторые враги меняют тип защиты прямо в бою. Враг с магическим уроном хорошо защищён от магии, а физический — от кликов.\n\nНе дай своему запасу секунд опуститься до нуля. Между боями время остановлено: изучи характеристики, потрать секунды своей жизни в магазине и посмотри подсказку к следующему врагу. Броня снижает получаемый физический урон, магическая защита — магический. Эти покупки действуют до конца забега, временные усиления — один бой.\n\nНажми на строку условия боя, чтобы открыть тактику. Кнопка паузы останавливает сражение. После смерти доступны новый забег и однократное воскрешение за рекламу.'
 },
 en:{
  title:'Time Thief',
  seo:'Steal seconds from time keepers, switch between taps and magic, upgrade your hero and challenge unique bosses in an endless fantasy clicker.',
  short:'Steal seconds, switch tactics and defeat the keepers of time.',
  about:'Time is both your health and your weapon. Every second counts: keepers constantly take your time, while your attacks recover only part of the damage you deal.\n\nTap for physical attacks or hold to cast magic. Enemies strongly resist their own damage type, so watch the action hint and change your approach. Spend your life seconds on clock capacity, attack power, armor and magic guard. Choose boss gifts and build your own set of upgrades.\n\nFace 16 regular enemy types, 10 distinct bosses, changing battle conditions and increasingly dangerous levels. Each boss has its own targets, seals, rhythm or heat mechanic, plus a second phase at half time. Your adventure continues beyond the final keeper: see how far you can push your personal best.\n\nProgress saves automatically. After defeat, an available rewarded ad can revive you once per run.',
  how:'On a computer, click an enemy with the left mouse button for physical damage. Hold the button to cast magic. On a phone, use short taps and touch-and-hold.\n\nThe hand icon beside the enemy tells you which action to use: tap or hold. Keep watching it, as some enemies switch defenses during battle. Magic enemies resist magic; physical enemies resist taps.\n\nKeep your time reserve above zero. Time stops between battles: inspect your stats, spend life seconds in the shop and check the recommended attack for the next enemy. Armor reduces incoming physical damage; magic guard reduces incoming magic damage. These purchases last for the whole run, while temporary boosts last one battle.\n\nSelect the battle condition to open tactics, or use the pause button to stop combat. After defeat, start a new run or watch an available rewarded ad for a single revival.'
 }
};
const keywords='кликер,время,магия,боссы,фэнтези,прокачка,приключение,бесконечная игра';
const comment='Unity WebGL 1.6.0. Язык читается из environment.i18n.lang после YaGames.init, до загрузки Unity: русский и английский, резервный язык — английский. LoadingAPI.ready вызывается после готовности интерфейса; GameplayAPI работает только в активном бою. Клик — физический урон, удержание — магия; рекомендуемый тип атаки показан рядом с врагом и перед следующим боем. При потере фокуса, открытии тактики, паузе и рекламе останавливаются бой и звук. Сохранения локальные, при доступности getPlayer/getData используются также облачные setData. Рекламное вознаграждение выдаётся только в onRewarded. Воскрешение — один раз за забег, по кнопке с указанием рекламы; без доступной рекламы кнопка отключена. Полноэкранная реклама запускается только между боями, после нескольких побед и выдержанного интервала. Без SDK игра сохраняет локальный прогресс. В меню предусмотрена таблица лидеров: без настроенной или доступной таблицы показан личный рекорд и сообщение о недоступности общего рейтинга.';
const limits={title:50,seo:160,short:70,about:1000,how:1000};
for(const [lang,data] of Object.entries(fields))for(const [key,value] of Object.entries(data)){if(value.length>limits[key])throw Error(lang+'/'+key+' exceeds '+limits[key]+': '+value.length);}
if(keywords.length>100||comment.length>2048)throw Error('Common field exceeds limit');
const data={version:'1.6.0',keywords,developerComment:comment,localizations:fields};
fs.writeFileSync(path.join(out,'listing.json'),JSON.stringify(data,null,2));
const labels={title:'Название',seo:'Описание для SEO',short:'Короткое описание',about:'Об игре',how:'Как играть'};
for(const lang of ['ru','en'])fs.writeFileSync(path.join(out,'texts-'+lang+'.txt'),Object.entries(fields[lang]).map(([key,value])=>labels[key]+' ('+value.length+'/'+limits[key]+')\n'+value).join('\n\n'));
fs.writeFileSync(path.join(out,'developer-comment.txt'),comment);
const esc=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const block=(title,value,limit)=>'<article><div class="row"><h3>'+esc(title)+'</h3><span>'+value.length+'/'+limit+'</span><button onclick="copy(this)">Скопировать</button></div><pre>'+esc(value)+'</pre></article>';
const html=`<!doctype html><html lang="ru"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Вор времени · материалы 1.6.0</title><style>
*{box-sizing:border-box}body{margin:0;background:#101827;color:#eee7d6;font:16px/1.6 system-ui,sans-serif}main{max-width:1050px;margin:auto;padding:50px 24px 90px}header{display:flex;gap:25px;align-items:center;margin-bottom:35px}header img{width:110px;height:110px}h1{font-size:36px;line-height:1.2;margin:8px 0}h2{font-size:26px;color:#e9cf93;margin-top:48px}h3{font-size:16px;margin:0}p{color:#c4ccda}a{color:#a1e3cd}table{border-collapse:collapse;width:100%;background:#192539}td{border-bottom:1px solid #354258;padding:13px 18px}td:first-child{width:31%;color:#e9cf93}article{border:1px solid #435065;padding:20px;margin:16px 0;background:#192539;border-radius:10px}.row{display:flex;align-items:center;gap:16px}.row span{margin-left:auto;color:#a8b6c9;font-size:13px}button{color:#e9eddc;background:#25594f;border:1px solid #79ab94;border-radius:6px;padding:8px 14px;cursor:pointer}pre{font:inherit;white-space:pre-wrap;overflow-wrap:anywhere;margin-bottom:0}.media{display:grid;grid-template-columns:1fr 1fr;gap:20px}.media img{width:100%;height:auto;border:1px solid #435065}.note{border-left:3px solid #bda268;padding:12px 20px;background:#1b2838}code{color:#dfc78e}@media(max-width:650px){main{padding:24px 16px}.media{display:block}.row{flex-wrap:wrap}header img{width:76px;height:76px}h1{font-size:27px}td{padding:10px;font-size:14px}}
</style><main><header><img src="icon-512.png" alt="Логотип"><div><small>МАТЕРИАЛЫ ДЛЯ ЯНДЕКС ИГР · 1.6.0</small><h1>Вор времени</h1><p>Тексты для копирования, изображения и запись реального геймплея.</p></div></header>
<p class="note">Архив игры: <b>TimeThief-Yandex-1.6.0.zip</b> — отдельный файл рядом с этим комплектом. В поле «Архив» загружай именно его. Этот комплект содержит материалы карточки игры.</p>
<h2>Общее</h2><table><tr><td>Версия</td><td>1.6.0</td></tr><tr><td>Платформы</td><td>Десктоп и Android. iOS добавляй при наличии Apple Team ID и после проверки на устройстве. ТВ не заявлен.</td></tr><tr><td>Ориентация</td><td>Любая: интерфейс адаптирован к портретному и альбомному экрану.</td></tr><tr><td>Языки</td><td>Русский и английский. Автоопределение через SDK при запуске.</td></tr><tr><td>Возраст</td><td>Рекомендуемый выбор — 12+ с учётом фэнтези-сражений и образов персонажей. Окончательную оценку даёт модерация.</td></tr><tr><td>Категории</td><td>Основная — «Кликеры». Вторая — «Ролевые», если такой пункт доступен в текущем списке.</td></tr><tr><td>Теги</td><td>Выбери доступные варианты, соответствующие: кликер, фэнтези, боссы, прокачка, одиночная, 2D, бесконечная.</td></tr><tr><td>Облачные сохранения</td><td>Включено. При недоступности платформы остаётся локальное сохранение.</td></tr><tr><td>Отсроченная публикация</td><td>На твоё усмотрение: включить для ручного выпуска после модерации; выключить для автоматического.</td></tr></table>
${block('Ключевые слова',keywords,100)}${block('Комментарий разработчика',comment,2048)}
${['ru','en'].map(lang=>'<h2>'+ (lang==='ru'?'Русский':'English')+'</h2>'+Object.entries(fields[lang]).map(([key,value])=>block(labels[key],value,limits[key])).join('')).join('')}
<h2>Иконка и обложки</h2><p>Иконка: <a href="icon-512.png">PNG 512×512</a>. Обложки: PNG 800×470, отдельные варианты для двух языков.</p><div class="media"><a href="cover-ru-800x470.png"><img src="cover-ru-800x470.png" alt="Русская обложка"></a><a href="cover-en-800x470.png"><img src="cover-en-800x470.png" alt="English cover"></a></div>
<h2>Скриншоты и видео</h2><p>Десктопные кадры — 1920×1080, мобильные — 1080×1920, JPEG максимального качества. Файлы <code>ru-*</code> — для русского описания, <code>en-*</code> — для английского. Добавь минимум два разных кадра для каждой выбранной платформы. Начни с <code>encounter</code> и <code>battle</code>; <code>menu</code> и <code>victory</code> — дополнительные.</p><p><a href="ru-desktop-gameplay.mp4">Горизонтальное видео MP4</a> · <a href="ru-mobile-gameplay.mp4">Вертикальное видео MP4</a>. Оба записаны из собранной игры с её звуком; длительность и параметры указаны в <a href="media-manifest.json">манифесте файлов</a>.</p>
<h2>Подключение таблицы лидеров</h2><p>Кнопка уже находится в главном меню. Создай в консоли числовую таблицу для максимального достигнутого уровня: ноль десятичных знаков, сортировка по убыванию. В файле <code>platform-config.js</code> укажи её точное техническое название в <code>leaderboardName</code>. Сейчас поле пустое: показывается личный рекорд и честное сообщение о недоступности общей таблицы.</p><p>После настройки достаточно обновить <code>platform-config.js</code> в WebGL-папке и снова запаковать содержимое. Повторная компиляция Unity для этого не требуется. Гостю доступен просмотр, отправка рекорда — только при разрешении SDK. Диалог авторизации самопроизвольно не открывается.</p>
<h2>Проверка черновика</h2><p>Открой сборку с debug-панелью Яндекса и чистым кешем. Индикатор I18N должен стать зелёным при загрузке. Через SDK mocks открой отдельно RU и EN и проверь меню и бой. Проверь настоящий показ рекламы, выдачу награды после просмотра и возврат из фоновой вкладки. Затем проверь восстановление облачного прогресса на другом устройстве.</p><p>Автоматические проверки SDK в комплекте используют подмену ответов платформы; они не заменяют этот прогон в настоящей консоли. Отправка на модерацию из этой задачи не выполнялась.</p>
<p>Официальные источники: <a href="https://yandex.ru/dev/games/doc/ru/console/add-new-game/draft">поля и форматы черновика</a>, <a href="https://yandex.ru/dev/games/doc/ru/requirements/2/7">возрастной рейтинг</a>, <a href="https://yandex.ru/dev/games/doc/ru/requirements/2/14">автоопределение языка</a>, <a href="https://yandex.ru/dev/games/doc/ru/sdk/sdk-leaderboard">SDK таблицы лидеров</a>. Проверено 14 сентября 2026.</p>
</main><script>async function copy(b){const text=b.closest('article').querySelector('pre').textContent;try{await navigator.clipboard.writeText(text);b.textContent='Скопировано';setTimeout(()=>b.textContent='Скопировать',1400)}catch{const r=document.createRange();r.selectNodeContents(b.closest('article').querySelector('pre'));getSelection().removeAllRanges();getSelection().addRange(r);b.textContent='Ctrl+C'}}</script></html>`;
fs.writeFileSync(path.join(out,'START-HERE.html'),html);
for(const file of ['icon-512.png','cover-ru-800x470.png','cover-en-800x470.png'])fs.copyFileSync('D:/Game/Release/Store/'+file,path.join(out,file));
for(const [lang,values] of Object.entries(fields))console.log(lang+' field lengths: '+Object.entries(values).map(([k,v])=>k+'='+v.length).join(', '));
