const fs=require('fs'),path=require('path'),{Resvg}=require('D:/Game/Work/tools/node_modules/@resvg/resvg-js');
const repo=path.resolve(__dirname,'..'),out='D:/Game/Release/Store';fs.mkdirSync(out,{recursive:true});
const font=repo+'/assets/fonts/Nunito-Bold.ttf';
const raster=key=>'data:image/png;base64,'+fs.readFileSync(repo+'/assets/raster/'+key+'.png').toString('base64');
const body=key=>fs.readFileSync(repo+'/assets/vector/'+key+'.svg','utf8').replace(/^<svg[^>]*>/,'').replace(/<\/svg>$/,'');
function render(file,svg,width){fs.writeFileSync(out+'/'+file,new Resvg(svg,{fitTo:{mode:'width',value:width},font:{fontFiles:[font],loadSystemFonts:false,defaultFontFamily:'Nunito'}}).render().asPng());}
const logo='data:image/png;base64,'+fs.readFileSync(repo+'/game/Assets/TimeThief/Resources/Art/logo.png').toString('base64');
render('icon-512.png','<svg xmlns="http://www.w3.org/2000/svg" width="512" height="512"><rect width="512" height="512" fill="#f7f1e5"/><image href="'+logo+'" x="20" y="20" width="472" height="472"/></svg>',512);
for(const lang of ['ru','en']){const title=lang==='ru'?['ВОР','ВРЕМЕНИ']:['TIME','THIEF'];const subtitle=lang==='ru'?'Укради секунду. Измени вечность.':'Steal a second. Change forever.';const svg=`<svg xmlns="http://www.w3.org/2000/svg" width="960" height="540" viewBox="0 0 960 540"><rect width="960" height="540" fill="#f7f1e5"/><circle cx="730" cy="270" r="246" fill="#eee4cf"/><circle cx="730" cy="270" r="218" fill="none" stroke="#cfb98f" stroke-width="2"/><image href="${raster('witch')}" x="484" y="0" width="470" height="535"/><image href="${raster('moth')}" x="770" y="305" width="170" height="210"/><image href="${logo}" x="51" y="32" width="116" height="116"/><g fill="#292d46" font-family="Nunito" font-weight="800"><text x="56" y="223" font-size="82">${title[0]}</text><text x="56" y="311" font-size="82">${title[1]}</text></g><text x="59" y="382" fill="#515c60" font-family="Nunito" font-size="21" font-weight="600">${subtitle}</text><rect x="58" y="427" width="257" height="52" rx="15" fill="#17695f"/><text x="186" y="461" text-anchor="middle" fill="#fffaf0" font-family="Nunito" font-size="22" font-weight="800">${lang==='ru'?'ВРЕМЯ — ТВОЯ СИЛА':'TIME IS YOUR POWER'}</text></svg>`;fs.writeFileSync(out+'/cover-'+lang+'.svg',svg);render('cover-'+lang+'.png',svg,960);}
console.log('Store artwork: '+out);
